on: pull_request

jobs:
 x1_job:
    runs-on: ubuntu-latest
    name: Dogfooding
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: x1 step
        uses: ./ # Uses an action in the root directory
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          override_owner: facebook
          override_repo: jest
